spring:
  datasource:
    url: jdbc:mysql://47.96.9.221:3306/spearow_mybatis?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 'ENC(WK/VS6OVEy+enXfjLAQ6TstiGRmsURNI)'
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapping.xml
  type-aliases-package: io.jovi.spearow.entity
