spring:
  datasource:
    url: jdbc:mysql://47.96.9.221:3306/spearow-mybatis?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: maojiawei7750

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: io.jovi.spearow.entity
